### ISSUE TITLE
Need Help in Node Count Problem

### ISSUE THREAD

**Issue by cansinakbas** [SpaceGroupUCL/Depthmap#10]
Hi, I conducted metric analysis for 5000 radii in depthmap , but node counts was seen  like a integration map; so  it is coloured in scale, I did not understand that why it is like that. How can I fix it ?

**Comment by varoudis** [comment]
I don't see why that is a problem... What you get is correct.
Please check the theory behind the analysis you performed.

The issues should be used for software problems.
Thanks
