### ISSUE TITLE
Point isovist

### ISSUE THREAD

**Issue by soumimuhuri** [SpaceGroupUCL/Depthmap#11]
Hi,

I am a research scholar, working on interaction spaces of high-rise group housing complexes. In this regard, I would like to draw isovist from centroid of a specific park,street and parking lot. Is it possible to import the points from CAD file to depthmap? If not, is there any other way to do so? 
I would be really grateful if you could kindly reply.

Regards,
Soumi Muhuri

**Comment by reemzako** [comment]
In the CAD file create a separate layer and pinpoint the locations which you want to create the isovists from, or you can even create a number of layers (for example one for centre of parks, one for the street locations, another for parking lots, etc.) and turn them all on
Once you import the file into Depthmap, create the isovists from the specified points and you can switch the layers on & off as necessary

**Comment by varoudis** [comment]
thanks Reem! I knew you were there expert for this! :+1:

**Comment by soumimuhuri** [comment]
Thanks a lot.

On Tue, Mar 15, 2016 at 4:03 AM, reemzako notifications@github.com wrote:

> In the CAD file create a separate layer and pinpoint the locations which
> you want to create the isovists from, or you can even create a number of
> layers (for example one for centre of parks, one for the street locations,
> another for parking lots, etc.) and turn them all on
> Once you import the file into Depthmap, create the isovists from the
> specified points and you can switch the layers on & off as necessary
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SpaceGroupUCL/Depthmap/issues/11#issuecomment-196549393
> .

## 

Soumi Muhuri, Research Scholar, Department of Architecture and Regional
Planning, IIT Kharagpur
