### ISSUE TITLE
[BUG] Depthmap Fails to Delete Axial Lines

### ISSUE THREAD

**Issue by ylerman** [SpaceGroupUCL/Depthmap#4]
There is a bug in the latest DepthMap versions related to manual deletion of axial lines.

The program deletes the wrong lines when trying to remove axial line or just crashes.

This bug happens on every .dxf and .grpah, so you can use gallery.dxf or any other 
1. Create the axial line map and 
2. Use "Reduce to Fewest Line Map..."
3. Go to  "Fewest-Line Map (Minimal)"
4. Press "Editable Off" to allow editing.
5. Select an axial line and try yo delete it.
6. A wrong line was removed or the program had crashed. 

This issue doesn't happen when using DepthMap 8.15.

Thank you very much,
     Yoav Lerman.
     Department of Geography and Human Environment
     Tel-Aviv University

**Comment by rimakanouna** [comment]
Hi
i just want to ask a question how to create a graph files because i can't use depthmap without a graph file please help me i really need it thank you

**Comment by SpaceGroupUCL** [comment]
this is not a general help forum. use the 'space syntax mail list'

**Comment by soumimuhuri** [comment]
Hi,
I am just unable to import few dxf files in depthmap 10. The programme stops functioning whenever I try to do that. What could be the possible reasons and how do I resolve this?

**Comment by varoudis** [comment]
please use the list for general questions next time!

Only DXF file with just straight line can be used! NO curves, polylines, circles etc! Clean your files first.

Tasos

**Comment by universityduhok** [comment]
Hi all,

I faced this problem before, you need first to be sure if your dxf file are
polygons (closed very well),

Also you make sure, if your drawings in one layer of lines (advice:try to
redraw your drawings in Autocad in polyline*)

Best

Wafaa

**Comment by soumimuhuri** [comment]
Thanks a lot.
